platform :ios, '13.0'

use_frameworks!

inhibit_all_warnings!

target 'app' do
	pod 'GraphQLite', '1.1.8'
	pod 'InputBarAccessoryView', '5.2.3'
	pod 'NYTPhotoViewer'
	pod 'PasscodeKit'
	pod 'ProgressHUD'
end
